### ISSUE TITLE
Is this dead? :(

### ISSUE THREAD

**Issue by willfaught** [pboyer/antlr4#45]
@pboyer @wjkohnen Are you guys still interested in fixing the remaining test failures and getting this thing pulled upstream? I feel like we're close, but it seems like you've lost interest. Should I move on?

**Comment by pboyer** [comment]
Hey @willfaught, 

My life got a bit more complicated when this project was open-sourced due to external reasons. It's tough to explain, but a big part of why I haven't been as active on this project as I'd like.

The good news is things are getting better in fits and starts. So, for the moment, I'm happy to review PR's and so on, but it's hard for me to put in a lot of time.

**Comment by willfaught** [comment]
OK, thanks for the update!
